In [1]:
import sys
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

sys.path.append('../Scripts')
from Data_Processing import DataProcessing

from tensorflow import keras
from keras.callbacks import ModelCheckpoint
from keras.models import load_model
from keras import backend as K
from datetime import datetime
from sklearn.preprocessing import PowerTransformer

import joblib

In [2]:
df = DataProcessing('../Data/test.csv')

In [3]:
df

,Lap_Number,Lap_Time,Lap_Improvement,S1,S1_Improvement,S2,S2_Improvement,S3,S3_Improvement,Kph,Elapsed,Driver_Name,Pit_Time,Team,Power,Location,Event,Air_Temp,Track_Temp,Humidity,Pressure,Wind_Speed,Wind_Direction,Rain
0,1,NaN,0,70.200,0,35.433,0,30.693,0,59.5,136.4,SB,15.666667,JR,250.0,Location 7,Qualifying Group 1,1925.000,192.000,7999.000,100674.000,1159.000,310.000,0.0
1,2,NaN,0,27.667,0,33.680,0,37.767,0,81.8,235.5,SB,15.666667,JR,250.0,Location 7,Qualifying Group 1,1911.000,192.000,8048.000,100673.000,216.000,313.000,0.0
2,3,NaN,2,24.688,2,29.309,2,27.111,2,100.0,316.6,SB,15.666667,JR,250.0,Location 7,Qualifying Group 1,1687.500,184.875,8258.375,100738.625,730.375,221.250,0.0
3,1,NaN,0,69.100,0,35.705,0,30.451,0,59.9,135.2,ACO,14.900000,DSo,250.0,Location 7,Qualifying Group 1,1925.000,192.000,7999.000,100674.000,1159.000,310.000,0.0
4,2,NaN,0,28.401,0,33.693,0,35.958,0,82.7,233.3,ACO,14.900000,DSo,250.0,Location 7,Qualifying Group 1,1911.000,192.000,8048.000,100673.000,216.000,313.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,2,NaN,2,22.648,2,21.002,2,23.438,2,126.4,298.5,ALOTTE,77.600000,TAG,250.0,Location 8,Qualifying Group 3,2362.125,267.000,4305.750,101330.375,635.750,192.875,0.0
416,1,NaN,0,171.200,0,26.054,0,25.676,0,38.0,222.9,SVANDOO,75.200000,Ml,250.0,Location 8,Qualifying Group 3,2406.000,351.000,4583.000,101031.000,329.000,231.000,0.0
417,2,NaN,4,22.401,2,20.984,2,23.293,2,127.1,289.6,SVANDOO,75.200000,Ml,250.0,Location 8,Qualifying Group 3,2362.125,267.000,4305.750,101330.375,635.750,192.875,0.0
418,1,NaN,0,162.800,0,22.288,0,27.709,0,39.8,212.8,PWEHRL,72.550000,TAG,250.0,Location 8,Qualifying Group 3,2406.000,351.000,4583.000,101031.000,329.000,231.000,0.0
419,2,NaN,2,22.374,4,21.119,2,23.621,2,126.3,279.9,PWEHRL,72.550000,TAG,250.0,Location 8,Qualifying Group 3,2362.125,267.000,4305.750,101330.375,635.750,192.875,0.0